apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ include "kc_namespace" . }}
data:
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_FEATURES: admin-fine-grained-authz:v1,token-exchange
  KC_BOOTSTRAP_ADMIN_USERNAME: tmpadmin
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ include "dbKeycloakHost" . }}
  KC_DB: postgres
  KC_DB_URL_PORT: {{ include "dbPort" . }}
  KC_DB_URL_DATABASE: {{ include "dbKeycloakName" . }}
  KC_DB_USERNAME: {{ include "dbUser" . }}
  KEYCLOAK_TOKEN_LIFE: {{ include "tokenLife" . }}
  KEYCLOAK_NAMESPACE: {{ include "kc_namespace" . }}
  KEYCLOAK_HOSTNAME: {{ .Values.host }}
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
  # PROXY_ADDRESS_FORWARDING: true
---
{{- $list_ns := list .Release.Namespace -}}
{{- if .Values.outboundMode -}}
    {{ $list_ns = append $list_ns (include "controller_namespace" .) }}
{{- end -}}

{{- range $list_ns }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ . }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ include "dbKeycloakHost" $ }}
  KC_DB_USERNAME: {{ include "dbUser" $ }}
---
{{- end }}
