"""Adding review status column

Revision ID: c578d820455d
Revises: 989f740f31f8
Create Date: 2025-03-03 10:09:20.891956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c578d820455d'
down_revision: Union[str, None] = 'b4ce486e95bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('review_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'review_status')
    # ### end Alembic commands ###
