"""Container Management

Revision ID: 989f740f31f8
Revises: 3d3999b8de6a
Create Date: 2025-01-13 16:15:50.187083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989f740f31f8'
down_revision: Union[str, None] = '3d3999b8de6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('needs_auth', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('ml', sa.Boolean(), nullable=True),
    sa.Column('dashboard', sa.Boolean(), nullable=True),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('containers')
    op.drop_table('registries')
    # ### end Alembic commands ###
