"""Added sha column to images

Revision ID: 50181f0b508c
Revises: c578d820455d
Create Date: 2025-10-15 16:44:32.671978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50181f0b508c'
down_revision: Union[str, None] = 'c578d820455d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('sha', sa.String(length=256), nullable=True))
    op.alter_column('containers', 'tag',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'tag',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('containers', 'sha')
    # ### end Alembic commands ###
