"""pydantic model migration

Revision ID: 63ed4b61151d
Revises: 8faa556d4f76
Create Date: 2026-03-17 16:06:59.887670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ed4b61151d'
down_revision: Union[str, None] = '8faa556d4f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('schema_read', sa.String(length=256), nullable=True))
    op.drop_column('datasets', 'schema')
    op.add_column('tasks', sa.Column('pod_status', sa.String(length=256), server_default='scheduled', nullable=True))
    op.execute("UPDATE tasks SET pod_status = status WHERE status IS NOT NULL")
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'pod_status')
    op.add_column('datasets', sa.Column('schema', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'schema_read')
    # ### end Alembic commands ###
