"""fast-api model migration

Revision ID: 4ed9f908f50a
Revises: 63ed4b61151d
Create Date: 2026-03-17 16:25:41.282345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed9f908f50a'
down_revision: Union[str, None] = '63ed4b61151d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit', 'api_function',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('audit', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalogues', 'version',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('catalogues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalogues', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('containers', 'ml',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('containers', 'dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('containers', 'registry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasets', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dictionaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dictionaries', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('registries', 'needs_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('registries', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('requests', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('tasks', 'pod_status',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'pod_status',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('requests', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('registries', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('registries', 'needs_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dictionaries', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dictionaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('datasets', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('containers', 'registry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('containers', 'dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('containers', 'ml',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('catalogues', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('catalogues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalogues', 'version',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('audit', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit', 'api_function',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('audit', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
