[tool.pytest.ini_options]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session

[pytest]
testpaths = src/
addopts = --cov=app --cov-report xml:artifacts/coverage.xml
required_plugins = pytest-cov
env =
  PGDATABASE=test_app
  PGPORT=5434
  PGUSER=admin
  PGPASSWORD=test_app
  KEYCLOAK_URL=http://keycloak:8080
  KEYCLOAK_REALM=FederatedNode
  KEYCLOAK_CLIENT=global
  KEYCLOAK_ADMIN=admin
  KEYCLOAK_ADMIN_PASSWORD=password1
  KC_BOOTSTRAP_ADMIN_USERNAME=tmpadmin
  KC_BOOTSTRAP_ADMIN_PASSWORD=password1
  KEYCLOAK_SECRET=qwtirtvJJ4PW4skOlW6Oifk2
  PYTHONPATH=/app
  RESULTS_PATH=/tmp/results
  TASK_POD_RESULTS_PATH=/mnt/data
  DEFAULT_NAMESPACE=default
  TASK_NAMESPACE=tasks
  KEYCLOAK_NAMESPACE=keycloak
  CLEANUP_AFTER_DAYS=1
  PUBLIC_URL=localhost:5000
  CLAIM_CAPACITY=100Mi
  CONTROLLER_NAMESPACE=fn-controller
  IMAGE_TAG='1.7.0'
  ALPINE_IMAGE=ghcr.io/aridhia-open-source/alpine:1.7.0
  STORAGE_CLASS=storage-backend
