apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'federatednode'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/r-casula/PHEMS_federated_node'
    path: k8s/federated-node
    targetRevision: main
    helm:
      # paste the custom helm values content in here
      values: |
        federatedNode:
          port: 5000
          volumes:
            results_path: /mnt/results
            task_pod_results_path: /mnt/data
    chart: federated-node
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
