# Default values for federated_node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pullPolicy: Always
create_db_deployment: true
local_development: true
smoketests: false
taskReview: true
cleanupTime: 3
host: &host phems-federatednode.net

backend:
  tag: 1.9.0
  volumes:
    results_path: /data/flask/results

keycloak:
  tag: 1.9.0

db:
  user: &userDB admin
  host: db.fn.svc
  port: &portDB 5432
  secret:
    name: local-db
    key: password
    value: local-db-secret

storage:
  capacity: 1Gi
  local:
    path: /data/flask
    dbpath: /data/db


global:
  host: *host
  delivery_url: federated-node.uksouth.analytixagility.aridhiadev.net

certs:
  frequency: 65

integrations:
  domains:
    - http://localhost:8088
    - https://phems-federatednode.net

whitelist:
  enabled: false
blacklist:
  enabled: false
tls:
  secretName: &tls my-tls-secret

cert-manager:
  enabled: false

ingress-nginx:
  enabled: false
  controller:
    extraArgs:
      default-ssl-certificate: qcfederatednode/my-tls-secret

outboundMode: true

## Sub Charts

### Gateway API
gatewayApi:
  installCRD: false

### Traefik
traefik:
  providers:
    kubernetesIngress:
      enabled: false
  enabled: false

fn-task-controller:
  idp:
    github: null
  storage:
    size: 100Mi
    local:
      path: /data/controller
  delivery:
    other:
      url: federated-node.uksouth.analytixagility.aridhiadev.net
      auth_type: AzCopy